
/* Création de la table users */
CREATE TABLE users (
		id INT(11) AUTO_INCREMENT PRIMARY KEY,
		user_id VARCHAR(255) UNIQUE NOT NULL ,
		username VARCHAR(255) NOT NULL,
		email VARCHAR(255) UNIQUE NOT NULL,
		password VARCHAR(255) NOT NULL,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);